module.exports = {
  turndown: {
    headingStyle: "atx",
    hr: "---",
    bulletListMarker: "-",
    codeBlockStyle: "indented",
    emDelimiter: "_",
    strongDelimiter: "**",
  },
  prettier: {
    parser: "markdown",
  },
  dict: {
    salles: {
      "1": ["HL", "Henri Langlois"],
      "2": ["GF", "Georges Franju"],
      "3": ["JE", "Jean Epstein"],
      "4": ["HO", "Hors les murs"],
      "5": ["LE", "Lotte Eisner"],
    },
    version: {
      "20": "VF",
      "21": "VO",
      "22": "VA",
      "160": "Autres",
    },
    sousTitres: {
      "23": "STF",
      "24": "STA",
      "163": "Autres",
    },
    intertitres: {
      "25": "INT. FR.",
      "26": "INT. ANG.",
      "164": "INT. ALL.",
      "165": "Autres",
    },
    format: {
      "27": "35 mm",
      "123": "16 mm",
      "124": "70 mm",
      "125": "Vidéo",
      "166": "Numérique",
      "224": "Super 8",
      "225": "8 mm",
      "237": "DCP",
    },
    mentionSeance: {
      "102": "Séance suivie d'une discussion avec ",
      "103": "Accompagnement musical par ",
      "247": "Séance présentée par ",
    },
    typeSeance: {
      "43": "Avant-première",
      "44": "Ouverture de la rétrospective",
      "45": "Projection avec sous-titrage pour sourds et malentendants",
      "159": "Projection spéciale",
    },
  },
  momentLocale: {
    fr: {
      months: [
        "janvier",
        "février",
        "mars",
        "avril",
        "mai",
        "juin",
        "juillet",
        "août",
        "septembre",
        "octobre",
        "novembre",
        "décembre",
      ],
      monthsShort: [
        "jan",
        "fév",
        "mar",
        "avr",
        "mai",
        "juin",
        "juil",
        "aoû",
        "sep",
        "oct",
        "nov",
        "déc",
      ],
      weekdays: [
        "Dimanche",
        "Lundi ",
        "Mardi ",
        "Mercredi ",
        "Jeudi ",
        "Vendredi ",
        "Samedi ",
      ],
      weekdaysShort: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
    },
  },
  countries: [
    ["AFG", "Afghanistan"],
    ["AGO", "Angola"],
    ["ALB", "Albanie"],
    ["ANT", "Antilles néerlandaises"],
    ["ARE", "Émirats arabes unis"],
    ["ARG", "Argentine"],
    ["ARM", "Arménie"],
    ["AUS", "Australie"],
    ["AUT", "Autriche"],
    ["AZE", "Azerbaïdjan"],
    ["BAH", "Bahamas"],
    ["BEL", "Belgique"],
    ["BEN", "Bénin"],
    ["BFA", "Burkina Faso"],
    ["BGD", "Bangladesh"],
    ["BGR", "Bulgarie"],
    ["BIH", "Bosnie-Herzégovine"],
    ["BMU", "Bermudes"],
    ["BOL", "Bolivie"],
    ["BRA", "Brésil"],
    ["BTN", "Bhoutan"],
    ["BWA", "Botswana"],
    ["CAN", "Canada"],
    ["CHE", "Suisse"],
    ["CHL", "Chili"],
    ["CHN", "Chine"],
    ["CHP", "Chypre"],
    ["CIV", "Côte d'Ivoire"],
    ["CMB", "Cambodge"],
    ["CMR", "Cameroun"],
    ["COG", "Congo"],
    ["COL", "Colombie"],
    ["CPV", "Cap-Vert"],
    ["CRI", "Costa Rica"],
    ["CRT", "Croatie"],
    ["CSK", "Tchécoslovaquie"],
    ["CUB", "Cuba"],
    ["CYM", "Îles Caïman"],
    ["DEU", "Allemagne"],
    ["DNK", "Danemark"],
    ["DOM", "République dominicaine"],
    ["DZA", "Algérie"],
    ["ECU", "Équateur"],
    ["EGY", "Égypte"],
    ["EPA", "Palestine"],
    ["ERT", "Érythrée"],
    ["ESP", "Espagne"],
    ["EST", "Estonie"],
    ["ETH", "Éthiopie"],
    ["FIN", "Finlande"],
    ["FRA", "France"],
    ["FRO", "Îles Féroé"],
    ["GAB", "Gabon"],
    ["GBR", "Grande-Bretagne"],
    ["GHA", "Ghana"],
    ["GIN", "Guinée-Bissau"],
    ["GOG", "Géorgie"],
    ["GRC", "Grèce"],
    ["GTM", "Guatemala"],
    ["HKG", "Hong-Kong"],
    ["HND", "Honduras"],
    ["HTI", "Haïti"],
    ["HUN", "Hongrie"],
    ["HVO", "Burkina-Faso"],
    ["IDN", "Indonésie"],
    ["INC", "Pays inconnu"],
    ["IND", "Inde"],
    ["IRL", "Irlande"],
    ["IRN", "Iran"],
    ["IRQ", "Irak"],
    ["ISL", "Islande"],
    ["ISR", "Israël"],
    ["ITA", "Italie"],
    ["JAM", "Jamaïque"],
    ["JOD", "Jordanie"],
    ["JPN", "Japon"],
    ["KAZ", "Kazakhstan"],
    ["KEN", "Kenya"],
    ["KGZ", "Kirghizistan"],
    ["KOR", "Corée"],
    ["KWT", "Koweit"],
    ["LAO", "Laos"],
    ["LBN", "Liban"],
    ["LBY", "Libyie"],
    ["LIE", "Liechtenstein"],
    ["LKA", "Sri Lanka"],
    ["LTU", "Lituanie"],
    ["LUX", "Luxembourg"],
    ["LVA", "Lettonie"],
    ["MAC", "Macédoine"],
    ["MAR", "Maroc"],
    ["MCO", "Monaco"],
    ["MDA", "Moldova"],
    ["MDG", "Madagascar"],
    ["MEX", "Mexique"],
    ["MLI", "Mali"],
    ["MLT", "Malte"],
    ["MMR", "Myanmar"],
    ["MNE", "Monténégro"],
    ["MNG", "Mongolie"],
    ["MOZ", "Mozambique"],
    ["MRT", "Mauritanie"],
    ["MYS", "Malaisie"],
    ["NER", "Niger"],
    ["NGA", "Nigéria"],
    ["NIC", "Nicaragua"],
    ["NLD", "Pays-Bas"],
    ["NOR", "Norvège"],
    ["NPL", "Népal"],
    ["NZL", "Nouvelle-Zélande"],
    ["PAK", "Pakistan"],
    ["PAN", "Panama"],
    ["PER", "Pérou"],
    ["PHL", "Philippines"],
    ["PNG", "Papouasie-Nouvelle-Guinée"],
    ["POL", "Pologne"],
    ["PRI", "Porto Rico"],
    ["PRK", "Corée du Nord"],
    ["PRT", "Portugal"],
    ["PRY", "Paraguay"],
    ["PSE", "Palestine"],
    ["PYF", "Polynésie française"],
    ["QAT", "Qatar"],
    ["RDA", "RDA"],
    ["RDJ", "Djibouti"],
    ["RFA", "RFA"],
    ["ROM", "Roumanie"],
    ["RTQ", "République tchèque"],
    ["RUS", "Russie"],
    ["RWA", "Rwanda"],
    ["SAL", "Salvador"],
    ["SAU", "Arabie saoudite"],
    ["SDN", "Soudan"],
    ["SEN", "Sénégal"],
    ["SER", "Serbie"],
    ["SGP", "Singapour"],
    ["SLN", "Slovénie"],
    ["SLQ", "Slovaquie"],
    ["SUN", "URSS"],
    ["SWE", "Suède"],
    ["SYC", "Seychelles"],
    ["SYR", "Syrie"],
    ["TCD", "Tchad"],
    ["TGO", "Togo"],
    ["THA", "Thaïlande"],
    ["TKT", "Tadjikistan"],
    ["TUN", "Tunisie"],
    ["TUR", "Turquie"],
    ["TWN", "Taïwan"],
    ["TZA", "Tanzanie"],
    ["UGA", "Ouganda"],
    ["UKR", "Ukraine"],
    ["URY", "Uruguay"],
    ["USA", "États-Unis"],
    ["UZB", "Ouzbékistan"],
    ["VEN", "Vénézuéla"],
    ["VNM", "Vietnam"],
    ["YEM", "Yemen"],
    ["YUG", "Yougoslavie"],
    ["ZAF", "Afrique du Sud"],
    ["ZAR", "Zaïre"],
    ["ZWE", "Zimbabwe"],
  ],
};
